CREATE TABLE AUTOR (
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(30),
	EMAIL VARCHAR(40)
);

CREATE TABLE LIVRO (
	ISBN VARCHAR(10) PRIMARY KEY,
	DESCRICAO VARCHAR(50),
	EDICAO VARCHAR(15)
);

CREATE TABLE LIVRO_AUTOR (
	ISBN VARCHAR(10),
	CPF VARCHAR(11),
	PRIMARY KEY (ISBN, CPF),
	FOREIGN KEY (ISBN) REFERENCES LIVRO(ISBN),
	FOREIGN KEY (CPF) REFERENCES AUTOR(CPF),
);

CREATE TABLE EMPRESTIMO (
	CLIENTE VARCHAR(30), 
	DATA DATE,
	ISBN VARCHAR(10),
	SITUACAO VARCHAR(10),
	PRIMARY KEY (CLIENTE, DATA, ISBN, SITUACAO),
	FOREIGN KEY (ISBN) REFERENCES LIVRO(ISBN)
);
